// *** WARNING: DO NOT MODIFY *** This is a generated Java source code!
//
// Generated by LF-ET 2.3.0 (231108A), https://www.lohrfink.de/lfet
// From decision table
// "D:/LF/Projekte/lfet-demo-pwchecker-java-spring-boot/src/main/resources/lfet/pwchecker/PwChecker.lfet"
// 08.11.2023 07:34
//

// Prolog Standard ---->
// profile LFET.Java.Prolog.Standard.Interface.Dt.ini not found
// used LF-ET 2.3.0 (231108A) build in default

package lfet.demo.pwchecker.java.spring.boot.service;

import javax.annotation.processing.Generated;
import org.springframework.stereotype.Component;
import lombok.RequiredArgsConstructor;

@Generated("LF-ET")
@Component
@RequiredArgsConstructor
class PwChecker_rulesEngine
{
    final lfet.demo.pwchecker.java.spring.boot.common.DecisionTableLoggingFacade decisionTableLoggingFacade;

    <T extends lfet.demo.pwchecker.java.spring.boot.common.IDecisionTableModelTraceable> void execute(PwChecker_iFace<T> iFace, T model)
    {

        // Prolog Standard <----

        int ruleGroup = 1;
        boolean exit = false;

        while ( !exit )
        {
            exit = true;

            if ( ruleGroup == 1 ) // Prüfschritt? 1 - Prüfen: Die Passwortlänge
            {
                if ( iFace._is(PwChecker_iFace.AnzahlZeichen.$LESS8, model) /* < 8 - weniger als 8 Zeichen */ )
                {
                    // Rule R01 ---->

                    // logging beforeRule
                    // PwChecker
                    decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",1,10,model);

                    iFace._do(PwChecker_iFace.AnforderungNichtErfuellt.$LENLESS8, model); // Len<8 - Das Passwort ist zu kurz, es muss 8 bis 20 Zeichen lang sein

                    ruleGroup = 2;
                    exit = false;

                    decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",1,10,model);

                    // Rule R01 <----
                }
                else if ( iFace._is(PwChecker_iFace.AnzahlZeichen.$820, model) /* 8 - 20 - 8 bis 20 Zeichen */ )
                {
                    // Rule R02 ---->

                    // logging beforeRule
                    // PwChecker
                    decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",2,10,model);

                    ruleGroup = 2;
                    exit = false;

                    decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",2,10,model);

                    // Rule R02 <----
                }
                else // Anzahl Zeichen? > 20 - mehr als 20 Zeichen
                {
                    // Rule R03 ---->

                    // logging beforeRule
                    // PwChecker
                    decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",3,10,model);

                    iFace._do(PwChecker_iFace.AnforderungNichtErfuellt.$LENGREATER20, model); // Len>20 - Das Passwort ist zu lang, es muss 8 bis 20 Zeichen lang sein

                    ruleGroup = 2;
                    exit = false;

                    decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",3,10,model);

                    // Rule R03 <----
                }
            }
            else if ( ruleGroup == 2 ) // Prüfschritt? 2 - Prüfen: Die Anzahl verschiedener Kleinbuchstaben  im Passwort
            {
                if ( iFace._is(PwChecker_iFace.AnzahlVerschiedeneKleinbuchstaben.$LESS2, model) /* < 2 - weniger als 2 */ )
                {
                    // Rule R04 ---->

                    // logging beforeRule
                    // PwChecker
                    decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",4,10,model);

                    iFace._do(PwChecker_iFace.AnforderungNichtErfuellt.$KB2, model); // KB2 - Das Passwort muss mindestens 2 verschiedene Kleinbuchstaben enthalten

                    ruleGroup = 3;
                    exit = false;

                    decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",4,10,model);

                    // Rule R04 <----
                }
                else // Anzahl verschiedene Kleinbuchstaben? >= 2 - 2 oder mehr
                {
                    // Rule R05 ---->

                    // logging beforeRule
                    // PwChecker
                    decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",5,10,model);

                    ruleGroup = 3;
                    exit = false;

                    decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",5,10,model);

                    // Rule R05 <----
                }
            }
            else if ( ruleGroup == 3 ) // Prüfschritt? 3 - Prüfen: Die Anzahl verschiedener Grossbuchstaben  im Passwort
            {
                if ( iFace._is(PwChecker_iFace.AnzahlVerschiedeneGrossbuchstaben.$LESS2, model) /* < 2 - weniger als 2 */ )
                {
                    // Rule R06 ---->

                    // logging beforeRule
                    // PwChecker
                    decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",6,10,model);

                    iFace._do(PwChecker_iFace.AnforderungNichtErfuellt.$GB2, model); // GB2 - Das Passwort muss mindestens 2 verschiedene Grossbuchstaben enthalten

                    ruleGroup = 4;
                    exit = false;

                    decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",6,10,model);

                    // Rule R06 <----
                }
                else // Anzahl verschiedene Grossbuchstaben? >= 2 - 2 oder mehr
                {
                    // Rule R07 ---->

                    // logging beforeRule
                    // PwChecker
                    decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",7,10,model);

                    ruleGroup = 4;
                    exit = false;

                    decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",7,10,model);

                    // Rule R07 <----
                }
            }
            else // Prüfschritt? 4 - Prüfen: Die Anzahl verschiedener Sonderzeichen  im Passwort
            {
                if ( iFace._is(PwChecker_iFace.AnzahlVerschiedeneZiffern.$LESS2, model) /* < 2 - weniger als 2 */ )
                {
                    if ( iFace._is(PwChecker_iFace.AnzahlVerschiedeneSonderzeichen.$LESS2, model) /* < 2 - weniger als 2 */ )
                    {
                        // Rule R08 ---->

                        // logging beforeRule
                        // PwChecker
                        decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",8,10,model);

                        iFace._do(PwChecker_iFace.AnforderungNichtErfuellt.$SZ2, model); // SZ2 - Das Passwort muss mindestens 2 verschiedene Ziffern oder Sonderzeichen enthalten

                        exit = true;

                        decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",8,10,model);

                        // Rule R08 <----
                    }
                    else // Anzahl verschiedene Sonderzeichen? >= 2 - 2 oder mehr
                    {
                        // Rule R09 ---->

                        // logging beforeRule
                        // PwChecker
                        decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",9,10,model);

                        exit = true;

                        decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",9,10,model);

                        // Rule R09 <----
                    }
                }
                else // Anzahl verschiedene Ziffern? >= 2 - 2 oder mehr
                {
                    // Rule R10 ---->

                    // logging beforeRule
                    // PwChecker
                    decisionTableLoggingFacade.traceBeforeRule("PwChecker","20231108.073450",10,10,model);

                    exit = true;

                    decisionTableLoggingFacade.traceAfterRule("PwChecker","20231108.073450",10,10,model);

                    // Rule R10 <----
                }
            }

        }

        // Epilog Standard ---->
        // profile LFET.Java.Epilog.Standard.Interface.Dt.ini not found
        // used LF-ET 2.3.0 (231108A) build in default

    }

}

// Epilog Standard <----

// End of generated Java source code
// Generated by LF-ET 2.3.0 (231108A), https://www.lohrfink.de/lfet
